### ISSUE TITLE
Review unit and integration AtomDB tests

### ISSUE THREAD

**Issue by eddiebrissow** [singnet/das-atom-db#203]
Links to EPIC https://github.com/singnet/das/issues/97

**Comment by angeloprobst** [comment]
@eddiebrissow @andre-senna 

https://github.com/singnet/das-atom-db/pull/212#pullrequestreview-2293192886 <-- check this comment.

Those cases must be investigated and fixed when possible. I left some `TODO` comments to highlight them.

Let's keep this ticket open to remind us.
