### ISSUE TITLE
Simplify Patterns

### ISSUE THREAD

**Issue by eddiebrissow** [singnet/das-atom-db#204]
Links to https://github.com/singnet/das/issues/97

Simplify Patterns (and other similar) index to store Handle -> Set of mathcing handles instead of Handle -> Pair(Handle, List of Handles) as we have now.

Need to review metta parser indexes if atomdb indexes change

**Comment by eddiebrissow** [comment]
Patterns already simplified, atomDB and metta parser, need check other indexes

**Comment by andre-senna** [comment]
All changed indexes need to be updated in the DAS MeTTa parser as well.
