### ISSUE TITLE
Add generic parameters in constructor of atom DBs

### ISSUE THREAD

**Issue by andre-senna** [singnet/das-atom-db#45]
* check what should go as parameters in each adapter
* add a parameter for `self.mongo_bulk_insertion_limit` in `redis_mongo`
* add a parameter for `self.mongo_bulk_insertion_limit` in `redis_mongo`

**Comment by andre-senna** [comment]
Perhaps this have already been partially implemented. This issue is about using kwargs in AtomDB classes.

**Comment by marcocapozzoli** [comment]
@andre-senna I don't understand this issue

**Comment by marcocapozzoli** [comment]
This has already been implemented
