### ISSUE TITLE
Avoid making document copy in database.py->_replace_keys()

### ISSUE THREAD

**Issue by andre-senna** [singnet/das-atom-db#56]

**Comment by levisingularity** [comment]
sugestoes:
- The current version unknow error ao criar nova versao (melhorar excecao quando o cli não conseguir pegar a versao)
- no script de release, nao rodar os testes unitarios e de integracao antes de publicar no openfaas da vultr as novas functions
- Criar comando para rodar apenas testes unit e integracao trigando os pipelines
- Criar script no das-cli para informar todas as versoes de todos os repos no github, no dockerhub, no servidor de dev e prod
- uma outra coisa que a gente pode colocar no script, buscar as versões mais atualizadas dos pacotes que são detendentes um do outro, por exemplo se a gente quiser atualizar só as functions porque gerou uma versão manual do query engine, o script buscar a versão atual do query engine e sugerir atualizar no serverless function
- gerar um arquivo de backup no momento que está rodando o script

**Comment by andre-senna** [comment]
Deprecated
